// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210409210406_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Actual_end_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_by")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Target_end_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_by")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated_on")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
