// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Actual_End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_By")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project_Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Target_End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_by")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated_on")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
